import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import ScrappingDataForm from "@/components/Forms/ScrappingDataForm";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Scrapping App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.background}>
        <h1 className={styles.title}>SCRAPPING RESULT</h1>
        <ScrappingDataForm />
      </main>
    </>
  );
}
